# Generated by Django 5.0.7 on 2024-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_client_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
